"""Schema field definitions for tap-colleqtive."""

from __future__ import annotations

from hotglue_singer_sdk import typing as th


def _field_schema(fields: dict[str, th.JSONTypeHelper]) -> dict:
    return th.PropertiesList(
        *[th.Property(name, field_type) for name, field_type in fields.items()]
    ).to_dict()


PRODUCT_FIELDS = {
    "product_number": th.StringType,
    "product_name": th.StringType,
    "barcode": th.StringType,
    "price": th.NumberType,
    "purchase_price": th.NumberType,
    "is_active": th.BooleanType,
    "moq": th.NumberType,
    "brand_code": th.StringType,
    "brand_description": th.StringType,
    "image_url": th.StringType,
    "product_url": th.StringType,
    "volume": th.StringType,
    "base_unit_name": th.StringType,
    "allow_decimal": th.BooleanType,
    "supplier_id": th.StringType,
    "supplier_name": th.StringType,
    "category_code": th.StringType,
    "promotion": th.StringType,
    "old_price": th.NumberType,
    "is_order_manually": th.BooleanType,
    "is_edit_replenishment": th.BooleanType,
    "is_edit_min_max": th.BooleanType,
    "is_counted": th.BooleanType,
    "is_expiration": th.BooleanType,
    "expiration_min_range": th.IntegerType,
    "deprecation_date": th.DateTimeType,
    "product_details": th.StringType,
    "margin_category": th.StringType,
    "is_stock": th.BooleanType,
    "attention_code": th.StringType,
    "referral_product_id": th.StringType,
    "reset_store_stock": th.BooleanType,
    "country_code": th.StringType,
    "promo_stores_allowed": th.StringType,
    "promo_stores_not_allowed": th.StringType,
    "units": th.StringType,
    "stores_allowed": th.StringType,
    "stores_not_allowed": th.StringType,
    "countries_allowed": th.StringType,
    "countries_not_allowed": th.StringType,
    "smallest_product_number": th.StringType,
    "smallest_quantity": th.NumberType,
    "price_lines": th.StringType,
    "is_promotion": th.BooleanType,
    "promotion_week": th.StringType,
    "barcodes_array": th.StringType,
    "purchase_unit_barcode": th.StringType,
    "purchase_unit_quantity": th.NumberType,
    "purchase_unit_name": th.StringType,
    "is_set": th.BooleanType,
    "set_product": th.StringType,
    "carrier_item_quantity": th.NumberType,
    "product_type": th.StringType,
    "average_weight": th.NumberType,
    "variant_factor": th.NumberType,
    "is_store_product": th.BooleanType,
    "color": th.StringType,
    "color_code": th.StringType,
    "size": th.StringType,
    "size_code": th.StringType,
    "variant_code": th.StringType,
    "variant_family": th.StringType,
    "general_ledger": th.StringType,
    "is_template": th.BooleanType,
    "shelf_label_layout": th.IntegerType,
    "shelf_label": th.BooleanType,
    "shelf_label_price": th.BooleanType,
    "shelf_label_quantity": th.IntegerType,
    "shelf_label_barcode": th.BooleanType,
    "price_compare_multiplier": th.NumberType,
    "price_compare_unit": th.StringType,
    "special_price": th.NumberType,
    "free_fields": th.StringType,
    "purchase_unit_product_number": th.StringType,
    "supplier_product_number": th.StringType,
    "edit_min_max_percentage": th.IntegerType,
}


STOCK_LOG_FIELDS = {
    "id": th.IntegerType,
    "last_modified_date": th.DateTimeType,
    "store_number": th.StringType,
    "product_number": th.StringType,
    "barcode": th.StringType,
    "quantity": th.NumberType,
    "location": th.IntegerType,
    "source": th.StringType,
    "reference": th.StringType,
    "reason_code": th.IntegerType,
    "reason_code_description": th.StringType,
    "stock_pool_1": th.NumberType,
    "stock_pool_2": th.NumberType,
    "stock_pool_3": th.NumberType,
    "stock_pool_4": th.NumberType,
    "stock_pool_5": th.NumberType,
    "stock_pool_6": th.NumberType,
    "stock_pool_7": th.NumberType,
    "stock_pool_8": th.NumberType,
    "stock_pool_9": th.NumberType,
    "stock_pool_10": th.NumberType,
    "counted_quantity": th.NumberType,
    "expected_quantity": th.NumberType,
    "app_user_name": th.StringType,
    "updated_on": th.DateTimeType,
    "created_on": th.DateTimeType,
    "price": th.NumberType,
    "cost_center": th.StringType,
    "purchase_unit_quantity": th.NumberType,
    "general_ledger_debit": th.StringType,
    "general_ledger_credit": th.StringType,
    "purchase_price": th.NumberType,
    "store_products_price": th.NumberType,
    "reference_id": th.IntegerType,
    "location_code": th.StringType,
    "customer_order_shipment_number": th.StringType,
    "customer_order_shipment_number_line_number": th.IntegerType,
    "customer_order_number": th.StringType,
    "customer_order_line_number": th.IntegerType,
    "moved_on": th.DateTimeType,
    "updated_by": th.StringType,
    "remarks": th.StringType,
    "orderno": th.StringType,
    "exception_image": th.StringType,
    "review_status": th.StringType,
    "counting_assignment_id": th.IntegerType,
    "counting_lines_remaining": th.IntegerType,
    "stock_pool": th.StringType,
    "location_tag": th.StringType,
    "counting_lines_remaining_stockpool": th.StringType,
}


STOCK_FIELDS = {
    "id": th.IntegerType,
    "product_number": th.StringType,
    "store_number": th.StringType,
    "category_code": th.StringType,
    "category_name": th.StringType,
    "product_description": th.StringType,
    "most_likely_quantity": th.NumberType,
    "most_likely_datetime": th.DateTimeType,
    "last_counted_datetime": th.DateTimeType,
    "last_expiry_datetime": th.DateTimeType,
    "validate_expiry_datetime": th.DateTimeType,
    "min": th.NumberType,
    "max": th.NumberType,
    "most_likely_pool_1": th.NumberType,
    "most_likely_pool_2": th.NumberType,
    "most_likely_pool_3": th.NumberType,
    "most_likely_pool_4": th.NumberType,
    "most_likely_pool_5": th.NumberType,
    "most_likely_pool_6": th.NumberType,
    "most_likely_pool_7": th.NumberType,
    "most_likely_pool_8": th.NumberType,
    "most_likely_pool_9": th.NumberType,
    "most_likely_pool_10": th.NumberType,
    "next_ordering_datetime": th.DateTimeType,
    "next_delivery_datetime": th.DateTimeType,
    "ordering_datetimes": th.StringType,
    "delivery_datetimes": th.StringType,
    "order_level": th.NumberType,
    "adjusted_order_level": th.NumberType,
    "group_code": th.StringType,
    "category_order": th.IntegerType,
    "attention_codes": th.StringType,
    "forecast": th.StringType,
    "price": th.NumberType,
    "referral_product": th.StringType,
    "forecast_array": th.StringType,
    "history_array": th.StringType,
    "average_array": th.StringType,
    "smallest_item_quantity": th.NumberType,
    "smallest_product_number": th.StringType,
    "is_stock": th.BooleanType,
    "promotion_week": th.StringType,
    "purchase_unit_name": th.StringType,
    "purchase_unit_quantity": th.NumberType,
    "demand_until_delivery": th.NumberType,
    "original_min": th.NumberType,
    "original_max": th.NumberType,
    "storeproduct_attention_codes": th.StringType,
    "last_expiry_updatedby": th.StringType,
    "last_loss_updatedby": th.StringType,
    "last_minmax_updatedby": th.StringType,
    "last_receipt_updatedby": th.StringType,
    "barcode": th.StringType,
    "is_replenishment": th.BooleanType,
}


BUY_ORDER_FIELDS = {
    "order_number": th.StringType,
    "store_number": th.StringType,
    "last_modified_date": th.DateTimeType,
    "order_type": th.StringType,
    "import_id": th.IntegerType,
    "datetime_created": th.DateTimeType,
    "datetime_expected": th.DateTimeType,
    "tracing_url": th.StringType,
    "supplier_code": th.StringType,
    "supplier_name": th.StringType,
    "no_of_containers": th.IntegerType,
    "updated_on": th.DateTimeType,
    "status": th.StringType,
    "store_gln": th.StringType,
    "is_downloaded": th.BooleanType,
    "external_reference_number": th.StringType,
    "store_origin": th.StringType,
    "order_lines": th.StringType,
}
